/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSportfolioCardsRouteImport } from './routes/products.sportfolio-cards'
import { Route as ProductsNowIqRouteImport } from './routes/products.now-iq'
import { Route as ProductsHolygrailrRouteImport } from './routes/products.holygrailr'
import { Route as ProductsBriktradeRouteImport } from './routes/products.briktrade'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSportfolioCardsRoute = ProductsSportfolioCardsRouteImport.update({
  id: '/sportfolio-cards',
  path: '/sportfolio-cards',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsNowIqRoute = ProductsNowIqRouteImport.update({
  id: '/now-iq',
  path: '/now-iq',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsHolygrailrRoute = ProductsHolygrailrRouteImport.update({
  id: '/holygrailr',
  path: '/holygrailr',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBriktradeRoute = ProductsBriktradeRouteImport.update({
  id: '/briktrade',
  path: '/briktrade',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/briktrade': typeof ProductsBriktradeRoute
  '/products/holygrailr': typeof ProductsHolygrailrRoute
  '/products/now-iq': typeof ProductsNowIqRoute
  '/products/sportfolio-cards': typeof ProductsSportfolioCardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/briktrade': typeof ProductsBriktradeRoute
  '/products/holygrailr': typeof ProductsHolygrailrRoute
  '/products/now-iq': typeof ProductsNowIqRoute
  '/products/sportfolio-cards': typeof ProductsSportfolioCardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/briktrade': typeof ProductsBriktradeRoute
  '/products/holygrailr': typeof ProductsHolygrailrRoute
  '/products/now-iq': typeof ProductsNowIqRoute
  '/products/sportfolio-cards': typeof ProductsSportfolioCardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/products/briktrade'
    | '/products/holygrailr'
    | '/products/now-iq'
    | '/products/sportfolio-cards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/products/briktrade'
    | '/products/holygrailr'
    | '/products/now-iq'
    | '/products/sportfolio-cards'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/products/briktrade'
    | '/products/holygrailr'
    | '/products/now-iq'
    | '/products/sportfolio-cards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/sportfolio-cards': {
      id: '/products/sportfolio-cards'
      path: '/sportfolio-cards'
      fullPath: '/products/sportfolio-cards'
      preLoaderRoute: typeof ProductsSportfolioCardsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/now-iq': {
      id: '/products/now-iq'
      path: '/now-iq'
      fullPath: '/products/now-iq'
      preLoaderRoute: typeof ProductsNowIqRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/holygrailr': {
      id: '/products/holygrailr'
      path: '/holygrailr'
      fullPath: '/products/holygrailr'
      preLoaderRoute: typeof ProductsHolygrailrRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/briktrade': {
      id: '/products/briktrade'
      path: '/briktrade'
      fullPath: '/products/briktrade'
      preLoaderRoute: typeof ProductsBriktradeRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsBriktradeRoute: typeof ProductsBriktradeRoute
  ProductsHolygrailrRoute: typeof ProductsHolygrailrRoute
  ProductsNowIqRoute: typeof ProductsNowIqRoute
  ProductsSportfolioCardsRoute: typeof ProductsSportfolioCardsRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsBriktradeRoute: ProductsBriktradeRoute,
  ProductsHolygrailrRoute: ProductsHolygrailrRoute,
  ProductsNowIqRoute: ProductsNowIqRoute,
  ProductsSportfolioCardsRoute: ProductsSportfolioCardsRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
